### ISSUE TITLE
alas, KIE broke the sandbox extended service download

### ISSUE THREAD

**Issue by goldfish1880** [PacktPublishing/AI-and-Business-Rules-for-Excel-Power-Users#1]
when you get to the Extended Services Setup page, see image below - 
![image](https://github.com/PacktPublishing/AI-and-Business-Rules-for-Excel-Power-Users/assets/166753421/a44fa9f7-05de-4600-ac74-52d1173d2ac0)
the download link gives a 404

**Comment by paulbrowne-irl** [comment]
Thanks for the heads up - although you've reported this issue in the book samples project, rather than direct in the KIE Project where the team will be able to read and address - they are at https://github.com/kiegroup

In the meantime, the sandbox is version controlled, the previous version (e.g. https://sandbox.kie.org/0.310/#/ ) may still work - Paul

**Comment by goldfish1880** [comment]
after much hunting. i did find the file under https://github.com/apache/incubator-kie-tools/releases

the prior version did not work.

i initially posted the issue here as it was not clear to me which project under kiegroup to let them know the sandbox was broken
